### ISSUE TITLE
Check/Update Button/Widget CSS customization examples

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/click2vox-com#635]
# Check/Update Button/Widget CSS customization examples

## Tasks

- [x] Review the customization info at https://github.com/voxbone-workshop/click2vox-com/wiki/Customize-Button-CSS

- [x] Review the customization info at https://github.com/voxbone-workshop/click2vox-com/wiki/Customize-Widget-CSS

### In both cases please expand and provide working examples for both cases. I guess a jsfiddle/codepen would be great 👍

**Comment by san983** [comment]
@fikrifirat https://developers.voxbone.com/how-to/style-click2vox-widget/ should be revisited as well, right?

**Comment by phiro56** [comment]
To create a customized button client needs only 2 css rules

.my-widget-style  .vxb-btn-style {}
.my-widget-style  .vxb-btn-style:hover {}

**Comment by phiro56** [comment]
<img width="221" alt="purple-btn" src="https://cloud.githubusercontent.com/assets/735483/24253420/eb71788c-0fa5-11e7-9bdd-ebfa1b94ea22.png">

Purple button example

.my-widget-style .vxb-btn-style {
  height: 40px ;
  padding: 0 20px ;
  background: #791e74 ;
  border: none;
  outline: none;
  line-height: 1 ;
  font-size: 14px ;
  font-weight: bold; 
  color: #ffffff;
  border-radius: 20px ;
}  

.my-widget-style .vxb-btn-style:hover {
  background: #550552 ;
}

**Comment by phiro56** [comment]
<img width="230" alt="blue-btn" src="https://cloud.githubusercontent.com/assets/735483/24253605/5fb9322a-0fa6-11e7-86f0-1b5dfe65d1e7.png">

Blue button example

.my-widget-style .vxb-btn-style {
  height: 40px ;
  padding: 0 15px ;
  background: #05bfd6 ;
  border: none;
  outline: none;
  line-height: 1 ;
  font-size: 14px ;
  font-weight: 300; 
  text-transform: uppercase;
  color: #ffffff;
  border-radius: 4px ;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 0px;;
}  

.my-widget-style .vxb-btn-style:hover {
  background: #04aabe ;
}

**Comment by phiro56** [comment]
To create a customized widget box a client needs to create 1 css rule.

Both ".vxb-widget-box" or ".my-widget-style"  can be used.

**Comment by phiro56** [comment]
<img width="281" alt="widget-box-dark" src="https://cloud.githubusercontent.com/assets/735483/24254224/f1f91424-0fa7-11e7-9dd8-a93ff3ec0187.png">

.vxb-widget-box {
  padding: 30px;
  background: #434242;
  border-radius: 4px ;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 0px;;
}

**Comment by san983** [comment]
Thanks @phiro56, could you please update/fix the wiki with that info/examples? https://github.com/voxbone-workshop/click2vox-com/wiki/Customize-Button-CSS

**Comment by fikrifirat** [comment]
@phiro56 @san983 These examples are really helpful, thanks. I will turn them into jsfiddles and update https://developers.voxbone.com/how-to/style-click2vox-widget/ It needs an update, anyway. 

However, I noticed that whenever we're talking about widget customisation, we're really talking about the button, not the call widget. Which, I think would be more helpful.

@phiro56 , how much of an effort would it be to also come up with 2 more styling examples for the call widget? We now have a default, gray one. Maybe one dark and one colourful widget would be a good idea to have?

Ideally, as a developer/customer; I'd probably like to know every single colour property to update. Can you make sure we have `vw-xx..` class names for each item that'd need to be coloured?

I also found a great tool that'd be useful, let me know if you have any ideas on animated examples using http://animista.net/

**Comment by san983** [comment]
Please @phiro56 check @fikrifirat's comments whenever you can 👍 

Also, @fikrifirat once you update https://developers.voxbone.com/how-to/style-click2vox-widget/ , should we just make a single entry in the Wiki to point there instead of the 2 we have today for customising widget + buttons❓

**Comment by phiro56** [comment]
@fikrifirat @san983 

Creating a couple of examples for the widget box should be fairly simple and quick.

Anything in particular you will like to see?

**Comment by fikrifirat** [comment]
@phiro56 We now have a default, grey one. Maybe one dark and one colourful widget examples?

**Comment by phiro56** [comment]
<img width="290" alt="screen shot 2017-03-29 at 3 07 22 pm" src="https://cloud.githubusercontent.com/assets/735483/24476668/786ee932-1491-11e7-982d-05904101fb3e.png">

.vxb-widget-box {
padding: 30px;
background: #243457;
border-radius: 4px ;
box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 0px;;
}

.my-widget-style  .vxb-btn-style {
height: 40px;
padding: 0 15px;
background: #e7e7e7;
border: none;
outline: none;
line-height: 1;
font-size: 14px;
font-weight: 300;
text-transform: uppercase;
color: #243457;
border-radius: 4px;
box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 0px;
}

.my-widget-style  .vxb-btn-style:hover {
background: #ffffff;
}

**Comment by phiro56** [comment]
<img width="289" alt="screen shot 2017-03-29 at 3 16 29 pm" src="https://cloud.githubusercontent.com/assets/735483/24477017/b8b11546-1492-11e7-83a6-db4e6c2288a2.png">

.vxb-widget-box { 
padding: 30px;
background: #37c0d7;
border-radius: 12px ;
box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 0px;;
}

.my-widget-style .vxb-btn-style {
height: 40px;
padding: 0 15px;
background: #454545;
border: none;
outline: none;
line-height: 1;
font-size: 14px;
font-weight: bold;
text-transform: uppercase;
color: #ffffff;
border-radius: 20px;
}

.my-widget-style .vxb-btn-style:hover {
background: #ffffff;
color: #454545
}

**Comment by fikrifirat** [comment]
@phiro56 
These are also `button` stylings. I meant we should provide guidelines on how to design the `call container`
![image](https://cloud.githubusercontent.com/assets/3737677/24541065/33a99098-15f6-11e7-96a8-87afb9d39a74.png)

**Comment by san983** [comment]
@fikrifirat can this one be closed?
