### ISSUE TITLE
The first time button is saved, the button label is changed to default value

### ISSUE THREAD

**Issue by rillma-r** [voxbone-workshop/click2vox-com#646]
**Description:**
When user creates a new button, and customize the button label, the first time when this button is saved, the button label is saved using the default value.

**Steps:**
1.	Login to https://click2vox.com
2.	Click Buttons
3.	Click “Add New Button”
4.	Customize the value of Button Label, like My Button
5.	Select some SIP URI
6.	Click Save Configuration

**Actual Result:**
The value in Button Label was changed to the default value ”Call Sales”
.
**Expected Result:**
The Button Label value should not change automatically.

**Screenshots:**
![button_label_changed_to_default_value](https://cloud.githubusercontent.com/assets/15701777/24048933/d1c05e2a-0b00-11e7-8f32-326b8d602700.png) 

**Google Docs:**
https://drive.google.com/open?id=0B6UHZqukl-7-T2VERUV6Wm0zN3c

**Comment by agonza1** [comment]
solved here: https://github.com/voxbone-workshop/click2vox-com/pull/679
