### ISSUE TITLE
Update documentation on all data tags

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/click2vox-com#656]
Currently, the only documentation we have that lists all the `data-` tags in click2vox.com and the portal widget generator is here: https://github.com/voxbone-workshop/portal-widget/wiki/About-the-Code-Snippet

This document has not been updated since September 2016 and is out of date.

## Actions

- [x] Update the document to show all of the currently available data tags
- [x] Be explicit on what tags are included by default in click2vox/portal widget generator
- [x] Be explicit in the default behavior if the tag excluded or included in the widget code
- [x] Highlight any differences between click2vox.com and the portal widget generator
- [x] Store/link/insert this document/text in the appropriate places for both click2vox.com and the portal widget generator repos

**Comment by emilianop11** [comment]
@fikrifirat I already finished this one. When you have some time, can you give it a look please?

**Comment by fikrifirat** [comment]
@emilianop11 It looks good & covers all properties :+1:
