### ISSUE TITLE
Why do we have <!DOCTYPE html> in the widget code?

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/click2vox-com#660]
Is there is a reason we have the `<DOCTYPE>` tag there? Isn’t `DOCTYPE` supposed to be the first tag and limited to one tag per page?

Might this cause a syntax checker to fail a page with the widget on it if that is included?

**Comment by san983** [comment]
Hi @chadwallacehart, this shouldn't affect any syntax check. But @agonza1 already addresses this problem in https://github.com/voxbone-workshop/click2vox-com/pull/650
