### ISSUE TITLE
Better handling of window.onbeforeunload

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/click2vox-com#673]
Do we currently override any behaviour in `function makeCall()`?

```
window.onbeforeunload = function (e) {
      voxbone.WebRTC.unloadHandler();
    };
```
If I want to warn my users with a message when there's an active call and they are trying to close/refresh the window and I do the following, it works before `makeCall()` but not after
```
window.onbeforeunload = function() {
  return "Your call will be disconnected, are you sure?";
};
```

Here are my suggestions
- [x] Investigate overriding `window.onbeforeunload`, are customers safe with `window.addEventListener("beforeunload",function(){return "There is an ongoing call, are you sure?";}, false);`
- [ ] Incorporate a warning message implementation as an option to prompt callers `.onbeforeunload`, when users try to refresh/navigate/close a page with an ongoing call
- [ ] Investigate exposing a `Boolean` of `onGoingCall` to the app, so they can check/poll if there's an ongoing call within the app.

**Comment by chadwallacehart** [comment]
There are 2 parts here:

1. Are we blocking other onbeforeunload events? Should we be using `window.addEventListener("beforeunload", myScript);` instead? If yes, then this is a bug that could conflict with customer sites and should be addressed ASAP.
2.  Graceful handling of users that close the window during a call - that one requires product definition and should be a separate issue

**Comment by chadwallacehart** [comment]
I believe this is a bug based on some quick tests with this fiddle: https://jsfiddle.net/chadwallacehart/zanh6jnv/
@san983 - can you assign?

**Comment by san983** [comment]
@emilianop11 let's work on this one together 👍

**Comment by san983** [comment]
1) Moving towards implementing `window.addEventListener` in order not to override any possible user behaviour
re: http://caniuse.com/#search=addEventListener

2) @fikrifirat please create a ticket for providing a warning to the user on closing a window with an ongoing call (if needed). Be aware that browser dialogs are at least not customizable in Firefox (re: https://bugzilla.mozilla.org/show_bug.cgi?id=1123986) 

3) @fikrifirat We already have the `isInCall()` method that allows the implementer know if there is an ongoing call

**Comment by san983** [comment]
1. Done and deployed!
