### ISSUE TITLE
.vw-rating-comment-question easily gets overridden

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/click2vox-com#694]
this happens on https://voxrec.me/recordings
![image](https://cloud.githubusercontent.com/assets/3737677/24540654/7f05953e-15f4-11e7-901c-8f29b241105f.png)

@phiro56 can you take a look?

**Comment by phiro56** [comment]
Added styles to target text wrap...

**Comment by san983** [comment]
Deployed
