### ISSUE TITLE
Encapsulate methods and events of Click2Vox in a global object

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/click2vox-com#696]
- The global object can be named `Click2Vox` by default. 
- It may be useful to have the ability to rename the object for reseller customers. (*i.e. change it to Click2VGP or Click2Fikri)
- It should encapsulate methods . (*i.e. `Click2Vox.makeCall`) and move exposing events to backlog , (*i.e. `Click2Vox.addEventListener`)

**Comment by agonza1** [comment]
For the last part missing of this issue `ability to rename the object for reseller customers. (*i.e. change it to Click2VGP or Click2Fikri)`.

 We could use the following:
`<script id="vxb-click2vox-script" async="async" src="http://localhost:3000/click2vox.js" data-customObject="click2voxCustom"></script>`

and then declare the configuration as `click2voxCustom = {did:"1234",...}`
What do you think?
