### ISSUE TITLE
Document click2vox.js and floating button features

### ISSUE THREAD

**Issue by agonza1** [voxbone-workshop/click2vox-com#710]

**Comment by agonza1** [comment]
https://github.com/voxbone-workshop/portal-widget/wiki/How-to-use-the-click2vox-SDK

**Comment by fikrifirat** [comment]
@agonza1 thanks for this, I can use this to create documentation/tutorial type materials. Can you make sure the `widget` you refer is the call container and not the button?

**Comment by agonza1** [comment]
I added a comment in the wiki how to specifying when I speak about call container or button

**Comment by san983** [comment]
Hi @fikrifirat @agonza1 can this one be closed?

**Comment by agonza1** [comment]
@san983 yes, this can be closed
