### ISSUE TITLE
WebRTC call rating errors

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/click2vox-com#718]
@chadwallacehart commented on [Thu Jul 06 2017](https://github.com/voxbone-workshop/voxbone-ai-frontend/issues/68)

![image](https://user-images.githubusercontent.com/6531125/27911942-47b39c80-625b-11e7-9825-1ebdca1503eb.png)

---

@san983 commented on [Thu Jul 06 2017](https://github.com/voxbone-workshop/voxbone-ai-frontend/issues/68#issuecomment-313499017)

When a user submits feedback through `click2vox.js` the library post that feedback both to `https://webrtc.voxbone.com/cgi-bin/post_logs.pl` and to the old `rating` endpoint in `click2vox.com`.

so, @chadwallacehart, as far as I know (and asked @agonza1 about too) we can remove that `ratings`  endpoint from `click2vox` and `portal widget generator` since despite they are being tried to be filled the data is not used or consulted for reporting.

(Removing the reason of this bug ticket)

**Comment by chadwallacehart** [comment]
So you are saying the `rating` endpoint is redundant and we are getting the data we need out of Kibana from the data posted to 'https://webrtc.voxbone.com/cgi-bin/post_logs.pl'??

**Comment by san983** [comment]
Exactly!

**Comment by san983** [comment]
https://github.com/voxbone-workshop/click2vox-com/pull/719
https://github.com/voxbone-workshop/portal-widget/pull/188
